service: product-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  logs: 
    restApi: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation

custom:
  documentation:
    api:
      info:
        version: v0.4.0
        title: AWS-shop
        description: Store API
    models:
      - name: productsResp
        contentType: application/json
        schema:
          type: array
          items: 
              $ref : '#/definitions/product'
      - name: productResp
        contentType: application/json
        schema:
          $ref : '#/definitions/product'
      - name: postProductReq
        contentType: application/json
        schema:
          type: object
          required:
            - title
            - price
            - stock
          properties:
            title: 
              type: string
            description:
              type: string
            price:
              type: integer
            stock:
              type: integer

  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  getAllProducts:
    handler: handler.getAllProducts
    events:
      - http:
          path: products
          method: get
          cors: true
          reqValidatorName: 'xMyRequestValidator'
  
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          reqValidatorName: 'xMyRequestValidator'
          request: 
            parameters: 
              paths: 
                productId: true
  postProduct:
    handler: handler.postProduct
    events:
      - http:
          path: products
          method: post
          cors: true
          reqValidatorName: 'xMyRequestValidator'
resources:
  Resources:
    xMyRequestValidator:
      Type: "AWS::ApiGateway::RequestValidator"
      Properties:
        Name: 'my-req-validator'
        RestApiId: 
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false
definitions:
  product:
    type: object
    properties:
      id:
        type: string
        format: uuid
      title: 
        type: string
      description:
        type: string
      price:
        type: integer
      stock:
        type: integer
