service: product-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  logs: 
    restApi: true
  apiGateway:
    shouldStartNameWithService: true


plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  documentation:
    api:
      info:
        version: v0.4.0
        title: AWS-shop
        description: Store API

  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  getAllProducts:
    handler: handler.getAllProducts
    events:
      - http:
          path: products
          method: get
          cors: true
  
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request: 
            parameters: 
              paths: 
                productId: true
  postProduct:
    handler: handler.postProduct
    events:
      - http:
          path: products
          method: post
          cors: true
          request:
            schema: 
              application/json: ${file(./models/productReq.model.json)}
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}